/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.rem.otdel;

import users.storegman.Details;
import users.admin.Admin;
import users.manager.Orders;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tigler
 */
public class LoginFrame extends javax.swing.JFrame {

    String managerLogin = "manager1";
    String managerParol = "manager11";

    String engineerLogin = "engineer1";
    String engineerParol = "engineer11";

    String storagemanLogin = "storageman1";
    String storagemanParol = "storageman11";

    String adminLogin = "admin";
    String adminParol = "admin";

    /**
     * Creates new form Login
     */
    public LoginFrame() {
        initComponents();
        jLabelIncorrect.setVisible(false);
        jLabelIncorrect.setForeground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabelLogin = new javax.swing.JLabel();
        jLabelParol = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jLabelIncorrect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Инициализация пользователя"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jLabelLogin.setText("Логин");

        jLabelParol.setText("Пароль");

        jPasswordField.setText("manager11");

        jTextFieldLogin.setText("manager1");

        jButtonEnter.setText("Войти");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jLabelIncorrect.setText("Логин или пароль некорректны");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIncorrect)
                            .addComponent(jLabelParol)
                            .addComponent(jLabelLogin))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(jPasswordField))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabelParol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIncorrect)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnter)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        // TODO add your handling code here:
        String login = jTextFieldLogin.getText();
        char[] parol = jPasswordField.getPassword();
        String password = String.valueOf(parol);
        if (login.equals(managerLogin) && password.equals(managerParol)) {
            Orders orders = null;
            try {
                orders = new Orders();
            } catch (SQLException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            orders.setVisible(true);
            this.dispose();
        } else if (login.equals(engineerLogin) && password.equals(engineerParol)) {

        } else if (login.equals(storagemanLogin) && password.equals(storagemanParol)) {
            try {
                Details details = new Details();
                details.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (login.equals(adminLogin) && password.equals(adminParol)) {
            Admin admin = new Admin();
            admin.setVisible(true);
            this.dispose();
        } else {
            jLabelIncorrect.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelIncorrect;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelParol;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldLogin;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
