/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users.admin;

import main.rem.otdel.ListenerCloseForm;
import main.rem.otdel.UpdatesDataInForms;
import otchet.alldetail.AllDetail;
import otchet.managerorder.ManagerOrder;
import otchet.notuseddetails.NotUsedDetails;
import otchet.timezakaz.TimeZakaz;
import spravochn.manager.Managers;
import spravochn.storegman.Storagemans;
import spravochn.engineer.Engenieers;

/**
 *
 * @author tigler
 */
public class Admin extends javax.swing.JFrame implements UpdatesDataInForms {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        addDataInTable();
    }
        @Override
    public void addDataInTable() {
        this.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButtonNotUsed = new javax.swing.JButton();
        jButtonOrderMeneger = new javax.swing.JButton();
        jButtonTimeOrder = new javax.swing.JButton();
        jButtonAllDetails = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuWorkers = new javax.swing.JMenu();
        jMenuItemManagers = new javax.swing.JMenuItem();
        jMenuItemEngineers = new javax.swing.JMenuItem();
        jMenuItemStoragemans = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Отчёты"));

        jButtonNotUsed.setText(" Не использующиеся детали");
        jButtonNotUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotUsedActionPerformed(evt);
            }
        });

        jButtonOrderMeneger.setText("Заказы конкректного менеджера");
        jButtonOrderMeneger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderMenegerActionPerformed(evt);
            }
        });

        jButtonTimeOrder.setText("Заказы за промежуток времени");
        jButtonTimeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeOrderActionPerformed(evt);
            }
        });

        jButtonAllDetails.setText("Все детали на складе");
        jButtonAllDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNotUsed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAllDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTimeOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOrderMeneger, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAllDetails)
                    .addComponent(jButtonTimeOrder))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNotUsed)
                    .addComponent(jButtonOrderMeneger))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jMenu2.setText("Файл");

        jMenuItem1.setText("Закрыть");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenuWorkers.setText("Пользователи");

        jMenuItemManagers.setText("Менеджеры");
        jMenuItemManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManagersActionPerformed(evt);
            }
        });
        jMenuWorkers.add(jMenuItemManagers);

        jMenuItemEngineers.setText("Инженеры");
        jMenuItemEngineers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEngineersActionPerformed(evt);
            }
        });
        jMenuWorkers.add(jMenuItemEngineers);

        jMenuItemStoragemans.setText("Кладовщики");
        jMenuItemStoragemans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStoragemansActionPerformed(evt);
            }
        });
        jMenuWorkers.add(jMenuItemStoragemans);

        jMenuBar1.add(jMenuWorkers);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManagersActionPerformed
        // TODO add your handling code here:
        Managers managers = new Managers();
        managers.setVisible(true);
    }//GEN-LAST:event_jMenuItemManagersActionPerformed

    private void jMenuItemEngineersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEngineersActionPerformed
        // TODO add your handling code here:
        Engenieers engenieers = new Engenieers();
        engenieers.setVisible(true);
    }//GEN-LAST:event_jMenuItemEngineersActionPerformed

    private void jMenuItemStoragemansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStoragemansActionPerformed
        // TODO add your handling code here:
        Storagemans storagemans = new Storagemans();
        storagemans.setVisible(true);
    }//GEN-LAST:event_jMenuItemStoragemansActionPerformed

    private void jButtonAllDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllDetailsActionPerformed
        AllDetail allDetail = new AllDetail();
        allDetail.setVisible(true);
        allDetail.setListenerCloseForm(new ListenerCloseForm(this));
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonAllDetailsActionPerformed

    private void jButtonTimeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimeOrderActionPerformed
        TimeZakaz timeZakaz = new TimeZakaz();
        timeZakaz.setVisible(true);
        timeZakaz.setListenerCloseForm(new ListenerCloseForm(this));
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonTimeOrderActionPerformed

    private void jButtonNotUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotUsedActionPerformed
        NotUsedDetails notUsedDetails = new NotUsedDetails();
        notUsedDetails.setVisible(true);
        notUsedDetails.setListenerCloseForm(new ListenerCloseForm(this));
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonNotUsedActionPerformed

    private void jButtonOrderMenegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderMenegerActionPerformed
        ManagerOrder managerOrder = new ManagerOrder();
        managerOrder.setVisible(true);
        managerOrder.setListenerCloseForm(new ListenerCloseForm(this));
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonOrderMenegerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAllDetails;
    private javax.swing.JButton jButtonNotUsed;
    private javax.swing.JButton jButtonOrderMeneger;
    private javax.swing.JButton jButtonTimeOrder;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemEngineers;
    private javax.swing.JMenuItem jMenuItemManagers;
    private javax.swing.JMenuItem jMenuItemStoragemans;
    private javax.swing.JMenu jMenuWorkers;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
