/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users.admin;

import spravochn.manager.Managers;
import spravochn.storegman.Storagemans;
import spravochn.engineer.Engenieers;

/**
 *
 * @author tigler
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuWorkers = new javax.swing.JMenu();
        jMenuItemManagers = new javax.swing.JMenuItem();
        jMenuItemEngineers = new javax.swing.JMenuItem();
        jMenuItemStoragemans = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Файл");
        jMenuBar1.add(jMenu2);

        jMenuWorkers.setText("Пользователи");

        jMenuItemManagers.setText("Менеджеры");
        jMenuItemManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManagersActionPerformed(evt);
            }
        });
        jMenuWorkers.add(jMenuItemManagers);

        jMenuItemEngineers.setText("Инженеры");
        jMenuItemEngineers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEngineersActionPerformed(evt);
            }
        });
        jMenuWorkers.add(jMenuItemEngineers);

        jMenuItemStoragemans.setText("Кладовщики");
        jMenuItemStoragemans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStoragemansActionPerformed(evt);
            }
        });
        jMenuWorkers.add(jMenuItemStoragemans);

        jMenuBar1.add(jMenuWorkers);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManagersActionPerformed
        // TODO add your handling code here:
        Managers managers = new Managers();
        managers.setVisible(true);
    }//GEN-LAST:event_jMenuItemManagersActionPerformed

    private void jMenuItemEngineersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEngineersActionPerformed
        // TODO add your handling code here:
        Engenieers engenieers = new Engenieers();
        engenieers.setVisible(true);
    }//GEN-LAST:event_jMenuItemEngineersActionPerformed

    private void jMenuItemStoragemansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStoragemansActionPerformed
        // TODO add your handling code here:
        Storagemans storagemans = new Storagemans();
        storagemans.setVisible(true);
    }//GEN-LAST:event_jMenuItemStoragemansActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEngineers;
    private javax.swing.JMenuItem jMenuItemManagers;
    private javax.swing.JMenuItem jMenuItemStoragemans;
    private javax.swing.JMenu jMenuWorkers;
    // End of variables declaration//GEN-END:variables
}
